##Makefile
##VIOX64
##Virtual Bios Hypervisor 4 AMD64 Fam10+ (&i64) 2 free & happy GPL3 hacking.
##Author: jhacks hack hersteller jhackher@gmail.com
##This program is released under the GNU GPL license v3 or later version, WHITHOUT ANY WARRANTY.
##A copy of the license should be found in jhacks.LICENSE.txt and/or COPYING.txt file.
##In any case latest version is in http://www.gnu.org/licenses/gpl.html
##
# viox64/src/hlib/Makefile v.0.1
hlibsrc = .
#
include $(hlibsrc)/hlib.make
#
